# Generated by Django 5.2.5 on 2025-08-31 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tip Title")),
                (
                    "title_ckb",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Tip Title"
                    ),
                ),
                (
                    "title_kmr",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Tip Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Tip Title"
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("email", "Email Communication"),
                            ("interview", "Interview"),
                            ("meeting", "Meeting/Presentation"),
                            ("phone", "Phone Call"),
                            ("networking", "Networking Event"),
                            ("application", "Application Process"),
                            ("visa", "Visa Interview"),
                            ("general", "General Communication"),
                        ],
                        max_length=20,
                        verbose_name="Communication Context",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country/Region"
                    ),
                ),
                ("content", models.TextField(verbose_name="Tip Content")),
                (
                    "content_ckb",
                    models.TextField(null=True, verbose_name="Tip Content"),
                ),
                (
                    "content_kmr",
                    models.TextField(null=True, verbose_name="Tip Content"),
                ),
                ("content_en", models.TextField(null=True, verbose_name="Tip Content")),
                ("example", models.TextField(blank=True, verbose_name="Example")),
                (
                    "example_ckb",
                    models.TextField(blank=True, null=True, verbose_name="Example"),
                ),
                (
                    "example_kmr",
                    models.TextField(blank=True, null=True, verbose_name="Example"),
                ),
                (
                    "example_en",
                    models.TextField(blank=True, null=True, verbose_name="Example"),
                ),
                (
                    "kurdish_context",
                    models.TextField(blank=True, verbose_name="Kurdish Context Notes"),
                ),
                (
                    "kurdish_context_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kurdish Context Notes"
                    ),
                ),
                (
                    "kurdish_context_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kurdish Context Notes"
                    ),
                ),
                (
                    "kurdish_context_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kurdish Context Notes"
                    ),
                ),
                (
                    "common_mistakes",
                    models.TextField(
                        blank=True, verbose_name="Common Mistakes to Avoid"
                    ),
                ),
                (
                    "common_mistakes_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Common Mistakes to Avoid"
                    ),
                ),
                (
                    "common_mistakes_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Common Mistakes to Avoid"
                    ),
                ),
                (
                    "common_mistakes_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Common Mistakes to Avoid"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "priority",
                    models.IntegerField(default=1, verbose_name="Display Priority"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Communication Tip",
                "verbose_name_plural": "Communication Tips",
                "ordering": ["-priority", "title"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Template Name"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("initial_inquiry", "Initial Inquiry to Supervisor"),
                            ("application_follow_up", "Application Follow-up"),
                            ("supervisor_introduction", "Supervisor Introduction"),
                            ("interview_request", "Interview Request"),
                            ("acceptance_response", "Acceptance Response"),
                            ("visa_inquiry", "Visa Inquiry"),
                            ("scholarship_inquiry", "Scholarship Inquiry"),
                            ("research_proposal", "Research Proposal Email"),
                            ("recommendation_request", "Recommendation Letter Request"),
                            ("general_inquiry", "General Inquiry"),
                        ],
                        max_length=30,
                        verbose_name="Template Type",
                    ),
                ),
                (
                    "formality_level",
                    models.CharField(
                        choices=[
                            ("very_formal", "Very Formal"),
                            ("formal", "Formal"),
                            ("semi_formal", "Semi-Formal"),
                            ("informal", "Informal"),
                        ],
                        max_length=20,
                        verbose_name="Formality Level",
                    ),
                ),
                (
                    "target_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Target Country"
                    ),
                ),
                (
                    "subject_line",
                    models.CharField(
                        max_length=200, verbose_name="Subject Line Template"
                    ),
                ),
                (
                    "subject_line_ckb",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Subject Line Template"
                    ),
                ),
                (
                    "subject_line_kmr",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Subject Line Template"
                    ),
                ),
                (
                    "subject_line_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Subject Line Template"
                    ),
                ),
                ("greeting", models.TextField(verbose_name="Greeting Template")),
                (
                    "greeting_ckb",
                    models.TextField(null=True, verbose_name="Greeting Template"),
                ),
                (
                    "greeting_kmr",
                    models.TextField(null=True, verbose_name="Greeting Template"),
                ),
                (
                    "greeting_en",
                    models.TextField(null=True, verbose_name="Greeting Template"),
                ),
                ("body", models.TextField(verbose_name="Email Body Template")),
                (
                    "body_ckb",
                    models.TextField(null=True, verbose_name="Email Body Template"),
                ),
                (
                    "body_kmr",
                    models.TextField(null=True, verbose_name="Email Body Template"),
                ),
                (
                    "body_en",
                    models.TextField(null=True, verbose_name="Email Body Template"),
                ),
                ("closing", models.TextField(verbose_name="Closing Template")),
                (
                    "closing_ckb",
                    models.TextField(null=True, verbose_name="Closing Template"),
                ),
                (
                    "closing_kmr",
                    models.TextField(null=True, verbose_name="Closing Template"),
                ),
                (
                    "closing_en",
                    models.TextField(null=True, verbose_name="Closing Template"),
                ),
                ("signature", models.TextField(verbose_name="Signature Template")),
                (
                    "signature_ckb",
                    models.TextField(null=True, verbose_name="Signature Template"),
                ),
                (
                    "signature_kmr",
                    models.TextField(null=True, verbose_name="Signature Template"),
                ),
                (
                    "signature_en",
                    models.TextField(null=True, verbose_name="Signature Template"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description/Usage Notes"
                    ),
                ),
                (
                    "description_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description/Usage Notes"
                    ),
                ),
                (
                    "description_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description/Usage Notes"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description/Usage Notes"
                    ),
                ),
                (
                    "cultural_notes",
                    models.TextField(
                        blank=True, verbose_name="Cultural Communication Notes"
                    ),
                ),
                (
                    "cultural_notes_ckb",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Cultural Communication Notes",
                    ),
                ),
                (
                    "cultural_notes_kmr",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Cultural Communication Notes",
                    ),
                ),
                (
                    "cultural_notes_en",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Cultural Communication Notes",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(default=list, verbose_name="Template Variables"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.CreateModel(
            name="ApplicationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_title",
                    models.CharField(max_length=300, verbose_name="Application Title"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning to Apply"),
                            ("preparing", "Preparing Application"),
                            ("submitted", "Application Submitted"),
                            ("under_review", "Under Review"),
                            ("interview", "Interview Stage"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                            ("deferred", "Deferred"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="Application Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("very_high", "Very High Priority"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priority Level",
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Application Deadline"
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Submission Date"
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Decision Date"
                    ),
                ),
                (
                    "supervisor_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Supervisor Name"
                    ),
                ),
                (
                    "supervisor_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Supervisor Email"
                    ),
                ),
                (
                    "admission_contact",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Admission Contact"
                    ),
                ),
                (
                    "admission_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Admission Email"
                    ),
                ),
                (
                    "research_area",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Research Area"
                    ),
                ),
                (
                    "funding_status",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Funding Status"
                    ),
                ),
                (
                    "application_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Application Fee",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "progress_notes",
                    models.TextField(blank=True, verbose_name="Progress Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destinations.studyprogram",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destinations.university",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Tracker",
                "verbose_name_plural": "Application Trackers",
                "ordering": ["-priority", "application_deadline"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV/Resume"),
                            ("cover_letter", "Cover Letter"),
                            ("motivation_letter", "Motivation Letter"),
                            ("research_proposal", "Research Proposal"),
                            ("transcript", "Academic Transcript"),
                            ("diploma", "Diploma/Certificate"),
                            ("recommendation", "Recommendation Letter"),
                            ("language_certificate", "Language Certificate"),
                            ("passport", "Passport Copy"),
                            ("portfolio", "Portfolio"),
                            ("writing_sample", "Writing Sample"),
                            ("test_scores", "Test Scores"),
                            ("other", "Other Document"),
                        ],
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Document Title"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="application_documents/",
                        verbose_name="Document File",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("submitted", "Submitted"),
                            ("needs_update", "Needs Update"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="Version")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Deadline"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Required Document"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="communications.applicationtracker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Document",
                "verbose_name_plural": "Application Documents",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("inquiry", "Initial Inquiry"),
                            ("follow_up", "Follow-up"),
                            ("application", "Application Related"),
                            ("interview", "Interview Related"),
                            ("acceptance", "Acceptance Related"),
                            ("visa", "Visa Related"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Email Type",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Recipient Email"),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Recipient Name"
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Subject")),
                ("body", models.TextField(verbose_name="Email Body")),
                (
                    "sent_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sent Date"),
                ),
                (
                    "response_received",
                    models.BooleanField(
                        default=False, verbose_name="Response Received"
                    ),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Response Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="communications.applicationtracker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="communications.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-sent_date"],
            },
        ),
    ]
