# Generated by Django 5.2.5 on 2025-08-31 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Country Name")),
                (
                    "name_ckb",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Country Name"
                    ),
                ),
                (
                    "name_kmr",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Country Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Country Name"
                    ),
                ),
                (
                    "name_sorani",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Sorani)"
                    ),
                ),
                (
                    "name_kurmanji",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Kurmanji)"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Country Code"
                    ),
                ),
                (
                    "flag_image",
                    models.ImageField(
                        blank=True, upload_to="flags/", verbose_name="Flag"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_ckb",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_kmr",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "official_language",
                    models.CharField(max_length=100, verbose_name="Official Language"),
                ),
                ("currency", models.CharField(max_length=50, verbose_name="Currency")),
                (
                    "academic_year_start",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Academic Year Start"
                    ),
                ),
                (
                    "application_deadlines",
                    models.TextField(
                        blank=True, verbose_name="General Application Deadlines"
                    ),
                ),
                (
                    "avg_tuition_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Average Tuition (USD)",
                    ),
                ),
                (
                    "avg_living_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Average Living Cost (USD)",
                    ),
                ),
                (
                    "student_visa_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Student Visa Type"
                    ),
                ),
                (
                    "visa_processing_time",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Visa Processing Time"
                    ),
                ),
                (
                    "work_permit_allowed",
                    models.BooleanField(
                        default=False, verbose_name="Work Permit Allowed for Students"
                    ),
                ),
                (
                    "post_study_work_visa",
                    models.BooleanField(
                        default=False, verbose_name="Post-Study Work Visa Available"
                    ),
                ),
                (
                    "kurdish_population",
                    models.TextField(
                        blank=True, verbose_name="Kurdish Community Information"
                    ),
                ),
                (
                    "kurdish_population_ckb",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish Community Information",
                    ),
                ),
                (
                    "kurdish_population_kmr",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish Community Information",
                    ),
                ),
                (
                    "kurdish_population_en",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish Community Information",
                    ),
                ),
                (
                    "kurdish_organizations",
                    models.TextField(blank=True, verbose_name="Kurdish Organizations"),
                ),
                (
                    "kurdish_organizations_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kurdish Organizations"
                    ),
                ),
                (
                    "kurdish_organizations_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kurdish Organizations"
                    ),
                ),
                (
                    "kurdish_organizations_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kurdish Organizations"
                    ),
                ),
                (
                    "application_difficulty",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="Application Difficulty (1-5)",
                    ),
                ),
                (
                    "living_quality",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="Living Quality (1-5)",
                    ),
                ),
                (
                    "study_quality",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="Study Quality (1-5)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="University Name"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Official Website"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="university_logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "university_type",
                    models.CharField(
                        choices=[
                            ("public", "Public University"),
                            ("private", "Private University"),
                            ("research", "Research Institution"),
                            ("applied", "University of Applied Sciences"),
                        ],
                        max_length=20,
                        verbose_name="University Type",
                    ),
                ),
                (
                    "established_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Established Year"
                    ),
                ),
                (
                    "world_ranking",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="World Ranking"
                    ),
                ),
                (
                    "national_ranking",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="National Ranking"
                    ),
                ),
                (
                    "student_population",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Student Population"
                    ),
                ),
                (
                    "international_students",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="International Students"
                    ),
                ),
                (
                    "instruction_languages",
                    models.CharField(
                        max_length=200, verbose_name="Languages of Instruction"
                    ),
                ),
                (
                    "international_office_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="International Office Email",
                    ),
                ),
                (
                    "admission_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Admission Email"
                    ),
                ),
                (
                    "kurdish_students_info",
                    models.TextField(
                        blank=True, verbose_name="Kurdish Students Information"
                    ),
                ),
                (
                    "kurdish_students_info_ckb",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish Students Information",
                    ),
                ),
                (
                    "kurdish_students_info_kmr",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish Students Information",
                    ),
                ),
                (
                    "kurdish_students_info_en",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish Students Information",
                    ),
                ),
                (
                    "kurdish_friendly_supervisors",
                    models.TextField(
                        blank=True, verbose_name="Kurdish-Friendly Supervisors"
                    ),
                ),
                (
                    "kurdish_friendly_supervisors_ckb",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish-Friendly Supervisors",
                    ),
                ),
                (
                    "kurdish_friendly_supervisors_kmr",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish-Friendly Supervisors",
                    ),
                ),
                (
                    "kurdish_friendly_supervisors_en",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Kurdish-Friendly Supervisors",
                    ),
                ),
                (
                    "academic_reputation",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="Academic Reputation (1-5)",
                    ),
                ),
                (
                    "research_opportunities",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="Research Opportunities (1-5)",
                    ),
                ),
                (
                    "international_support",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="International Student Support (1-5)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universities",
                        to="destinations.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Program Name")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("phd", "PhD"),
                            ("postdoc", "Postdoctoral"),
                            ("professional", "Professional Program"),
                        ],
                        max_length=20,
                        verbose_name="Program Level",
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(max_length=200, verbose_name="Field of Study"),
                ),
                (
                    "duration_months",
                    models.IntegerField(verbose_name="Duration (months)"),
                ),
                (
                    "credits",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Credits"
                    ),
                ),
                (
                    "language_of_instruction",
                    models.CharField(
                        max_length=100, verbose_name="Language of Instruction"
                    ),
                ),
                (
                    "min_gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Minimum GPA",
                    ),
                ),
                (
                    "language_requirements",
                    models.TextField(blank=True, verbose_name="Language Requirements"),
                ),
                (
                    "language_requirements_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Language Requirements"
                    ),
                ),
                (
                    "language_requirements_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Language Requirements"
                    ),
                ),
                (
                    "language_requirements_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Language Requirements"
                    ),
                ),
                (
                    "other_requirements",
                    models.TextField(blank=True, verbose_name="Other Requirements"),
                ),
                (
                    "other_requirements_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Other Requirements"
                    ),
                ),
                (
                    "other_requirements_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Other Requirements"
                    ),
                ),
                (
                    "other_requirements_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Other Requirements"
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Application Deadline"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Program Start Date"
                    ),
                ),
                (
                    "tuition_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tuition Fee",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "scholarships_available",
                    models.BooleanField(
                        default=False, verbose_name="Scholarships Available"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Program Description"),
                ),
                (
                    "description_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Program Description"
                    ),
                ),
                (
                    "description_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Program Description"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Program Description"
                    ),
                ),
                (
                    "career_prospects",
                    models.TextField(blank=True, verbose_name="Career Prospects"),
                ),
                (
                    "career_prospects_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Career Prospects"
                    ),
                ),
                (
                    "career_prospects_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Career Prospects"
                    ),
                ),
                (
                    "career_prospects_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Career Prospects"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="destinations.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Program",
                "verbose_name_plural": "Study Programs",
                "ordering": ["university__name", "level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Scholarship Name"),
                ),
                (
                    "provider",
                    models.CharField(
                        max_length=200, verbose_name="Provider/Organization"
                    ),
                ),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Scholarship"),
                            ("partial", "Partial Scholarship"),
                            ("tuition", "Tuition Only"),
                            ("living", "Living Expenses Only"),
                            ("research", "Research Grant"),
                        ],
                        max_length=20,
                        verbose_name="Scholarship Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "eligibility_criteria",
                    models.TextField(verbose_name="Eligibility Criteria"),
                ),
                (
                    "eligibility_criteria_ckb",
                    models.TextField(null=True, verbose_name="Eligibility Criteria"),
                ),
                (
                    "eligibility_criteria_kmr",
                    models.TextField(null=True, verbose_name="Eligibility Criteria"),
                ),
                (
                    "eligibility_criteria_en",
                    models.TextField(null=True, verbose_name="Eligibility Criteria"),
                ),
                (
                    "kurdish_specific",
                    models.BooleanField(
                        default=False, verbose_name="Kurdish-Specific Scholarship"
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Application Deadline"
                    ),
                ),
                (
                    "application_process",
                    models.TextField(blank=True, verbose_name="Application Process"),
                ),
                (
                    "application_process_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Process"
                    ),
                ),
                (
                    "application_process_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Process"
                    ),
                ),
                (
                    "application_process_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Process"
                    ),
                ),
                (
                    "required_documents",
                    models.TextField(blank=True, verbose_name="Required Documents"),
                ),
                (
                    "required_documents_ckb",
                    models.TextField(
                        blank=True, null=True, verbose_name="Required Documents"
                    ),
                ),
                (
                    "required_documents_kmr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Required Documents"
                    ),
                ),
                (
                    "required_documents_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Required Documents"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_ckb",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_kmr",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to="destinations.country",
                    ),
                ),
                (
                    "eligible_programs",
                    models.ManyToManyField(
                        blank=True,
                        to="destinations.studyprogram",
                        verbose_name="Eligible Programs",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to="destinations.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scholarship",
                "verbose_name_plural": "Scholarships",
                "ordering": ["-application_deadline", "name"],
            },
        ),
    ]
