# Generated by Django 5.2.5 on 2025-08-31 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Template Name"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic CV"),
                            ("professional", "Professional Resume"),
                            ("research", "Research-Focused CV"),
                            ("creative", "Creative Portfolio"),
                        ],
                        max_length=20,
                        verbose_name="Template Type",
                    ),
                ),
                (
                    "country_style",
                    models.CharField(
                        choices=[
                            ("us", "US Style"),
                            ("uk", "UK Style"),
                            ("eu", "European Style"),
                            ("canada", "Canadian Style"),
                            ("australia", "Australian Style"),
                            ("international", "International Style"),
                        ],
                        max_length=20,
                        verbose_name="Country Style",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        upload_to="cv_templates/",
                        verbose_name="Template File",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        upload_to="cv_previews/",
                        verbose_name="Preview Image",
                    ),
                ),
                (
                    "sections_order",
                    models.JSONField(default=list, verbose_name="Sections Order"),
                ),
                (
                    "formatting_guidelines",
                    models.TextField(blank=True, verbose_name="Formatting Guidelines"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CV Template",
                "verbose_name_plural": "CV Templates",
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Resume Title"),
                ),
                (
                    "target_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Target Country"
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Target Field"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                (
                    "kurdish_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kurdish Name"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Website/Portfolio"),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "professional_summary",
                    models.TextField(blank=True, verbose_name="Professional Summary"),
                ),
                (
                    "objective",
                    models.TextField(blank=True, verbose_name="Career Objective"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to="generated_cvs/",
                        verbose_name="Generated PDF",
                    ),
                ),
                (
                    "doc_file",
                    models.FileField(
                        blank=True,
                        upload_to="generated_cvs/",
                        verbose_name="Generated DOC",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Resume"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resume_builder.cvtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal Article"),
                            ("conference", "Conference Paper"),
                            ("book", "Book"),
                            ("chapter", "Book Chapter"),
                            ("thesis", "Thesis"),
                            ("report", "Technical Report"),
                            ("patent", "Patent"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Publication Type",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                ("authors", models.CharField(max_length=500, verbose_name="Authors")),
                (
                    "publication_venue",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Journal/Conference/Publisher",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Publication Date"
                    ),
                ),
                (
                    "volume",
                    models.CharField(blank=True, max_length=20, verbose_name="Volume"),
                ),
                (
                    "issue",
                    models.CharField(blank=True, max_length=20, verbose_name="Issue"),
                ),
                (
                    "pages",
                    models.CharField(blank=True, max_length=20, verbose_name="Pages"),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=200, verbose_name="DOI"),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("abstract", models.TextField(blank=True, verbose_name="Abstract")),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Keywords"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="resume_builder.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-publication_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("work", "Work Experience"),
                            ("research", "Research Experience"),
                            ("internship", "Internship"),
                            ("volunteer", "Volunteer Work"),
                            ("teaching", "Teaching Experience"),
                            ("project", "Project Experience"),
                        ],
                        max_length=20,
                        verbose_name="Experience Type",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=200, verbose_name="Job Title/Position"),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=200, verbose_name="Organization/Company"
                    ),
                ),
                (
                    "company_city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "company_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Current Position"),
                ),
                ("description", models.TextField(verbose_name="Job Description")),
                (
                    "achievements",
                    models.TextField(blank=True, verbose_name="Key Achievements"),
                ),
                (
                    "skills_used",
                    models.TextField(blank=True, verbose_name="Skills Used"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="resume_builder.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("diploma", "Diploma"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("phd", "PhD"),
                            ("postdoc", "Postdoctoral"),
                            ("certificate", "Certificate"),
                        ],
                        max_length=20,
                        verbose_name="Degree Level",
                    ),
                ),
                (
                    "degree_title",
                    models.CharField(max_length=200, verbose_name="Degree Title"),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Field of Study"
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(max_length=200, verbose_name="Institution Name"),
                ),
                (
                    "institution_city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "institution_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="Currently Studying"
                    ),
                ),
                (
                    "gpa",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="GPA/Grade"
                    ),
                ),
                (
                    "thesis_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Thesis Title"
                    ),
                ),
                (
                    "supervisor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Supervisor"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "achievements",
                    models.TextField(blank=True, verbose_name="Achievements/Honors"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="resume_builder.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Award"),
                            ("research", "Research Award"),
                            ("professional", "Professional Award"),
                            ("scholarship", "Scholarship"),
                            ("competition", "Competition Award"),
                            ("honor", "Honor/Recognition"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Award Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Award Title")),
                (
                    "issuing_organization",
                    models.CharField(
                        max_length=200, verbose_name="Issuing Organization"
                    ),
                ),
                ("date_received", models.DateField(verbose_name="Date Received")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="resume_builder.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "ordering": ["-date_received", "order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Skills"),
                            ("language", "Language Skills"),
                            ("software", "Software Skills"),
                            ("research", "Research Skills"),
                            ("interpersonal", "Interpersonal Skills"),
                            ("other", "Other Skills"),
                        ],
                        max_length=20,
                        verbose_name="Skill Category",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Skill Name")),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                            ("native", "Native"),
                        ],
                        max_length=20,
                        verbose_name="Proficiency Level",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Years of Experience"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resume_builder.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["category", "order"],
            },
        ),
    ]
