# Generated by Django 5.2.5 on 2025-08-31 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("destinations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                (
                    "name_sorani",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Sorani)"
                    ),
                ),
                (
                    "name_kurmanji",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Kurmanji)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_ckb",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_kmr",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon Class"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="Category Color"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.resourcecategory",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Category",
                "verbose_name_plural": "Resource Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Guide Title")),
                (
                    "title_ckb",
                    models.CharField(
                        max_length=300, null=True, verbose_name="Guide Title"
                    ),
                ),
                (
                    "title_kmr",
                    models.CharField(
                        max_length=300, null=True, verbose_name="Guide Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=300, null=True, verbose_name="Guide Title"
                    ),
                ),
                (
                    "guide_type",
                    models.CharField(
                        choices=[
                            ("country", "Country Guide"),
                            ("university", "University Guide"),
                            ("process", "Process Guide"),
                            ("visa", "Visa Guide"),
                            ("scholarship", "Scholarship Guide"),
                            ("career", "Career Guide"),
                            ("language", "Language Guide"),
                            ("cultural", "Cultural Guide"),
                            ("general", "General Guide"),
                        ],
                        max_length=20,
                        verbose_name="Guide Type",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Difficulty Level",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Summary")),
                (
                    "summary_ckb",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "summary_kmr",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("content_ckb", models.TextField(null=True, verbose_name="Content")),
                ("content_kmr", models.TextField(null=True, verbose_name="Content")),
                ("content_en", models.TextField(null=True, verbose_name="Content")),
                (
                    "steps",
                    models.JSONField(blank=True, default=list, verbose_name="Steps"),
                ),
                (
                    "estimated_reading_time",
                    models.IntegerField(
                        default=10, verbose_name="Estimated Reading Time (minutes)"
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(auto_now=True, verbose_name="Last Updated"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Views")),
                (
                    "helpful_votes",
                    models.IntegerField(default=0, verbose_name="Helpful Votes"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL Slug")),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_description_ckb",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_description_kmr",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_description_en",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        null=True,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Keywords"
                    ),
                ),
                (
                    "keywords_ckb",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Keywords"
                    ),
                ),
                (
                    "keywords_kmr",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Keywords"
                    ),
                ),
                (
                    "keywords_en",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Keywords"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured Guide"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="destinations.country",
                        verbose_name="Target Country",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="destinations.university",
                        verbose_name="Target University",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resources.resourcecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide",
                "verbose_name_plural": "Guides",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
